#!/usr/bin/env bash

# Directory containing this script
path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

python3 -m venv "${path}/pyenv" &&\
source "${path}/pyenv/bin/activate" &&\
pip install --upgrade pip &&\
pip install "${path}"
